### ISSUE TITLE
Errors during Strain Simulation (de novo mode)

### ISSUE THREAD

**Issue by Ettore1024** [CAMI-challenge/CAMISIM#132]
Hi and thank you very much for developing CAMISIM!

I have been using CAMISIM for two months and I have encountered three errors during the strain simulation in the de novo mode. I think I have already fixed them; however, I would like to show you the solutions I found, in order to hear your opinion.

The first error is: 

`ERROR: [MetagenomeSimulationPipeline] Not enough data to draw. `

It appears only during the strain simulation in the de novo modality, even if both `genomes_total` and `genomes_real` are equal to or smaller than the number of genomes I have in input. I found out that a solution for this error is to change `genomes_real` into `num_real_genomes`, which is compatible with what you have suggested in the Issue #100. I wish to inform you that in the Configuration File Options page on the Wiki of CAMISIM, the parameter `genomes_real` is not modified into `num_real_genomes`, as well as in `mini_config.ini` in the `defaults` folder (i.e. the configuration file of the test run).

The second error is: 
```
Can’t locate simujobparams.pm in @INC (you may need to install the simujobparams module) (@INC contains: ...)
ERROR: [MetagenomeSimulationPipeline] [Errno 2] No such file or directory: '/tmp/tmpi4gols2n/Genome4.0.strains/Taxon008.fasta' -> '/tmp/tmpi4gols2n/Genome4.0.strains/simulated_Genome4.0.Taxon008.fna' in line 83
```
It seems to be an error associated to Perl. I fixed it by using the command `export PERL5LIB='/path/to/…/scripts/StrainSimulationWrapper/sgEvolver/simulation_dir/'` every time before a run with strain simulation, so that the `simujobparams.pm` file can be found. I do not know if the problem is due to the way I installed Perl5. 
I wonder if there is another way to solve it permanently.

The last error is:

`ERROR: [MetagenomeSimulationPipeline] dictionary changed size during iteration in line 83. `

It seems to be a Python error, which occurs, during the strain simulation, in lines 459 and 504 of the `strainsimulationwrapper.py` file with the iterations: 
`for genome_id in genome_id_to_file_path_genome.keys():`
I fixed it creating a copy of the `genome_id_to_file_path_genome` dictionary that I used only for the iterations, i.e. something like:
```
genome_id_to_file_path_genome_copy = genome_id_to_file_path_genome.copy()
for genome_id in genome_id_to_file_path_genome_copy.keys():
       #code…
```
Thanks in advance!
All the best,
Ettore

**Comment by AlphaSquad** [comment]
Thank you very much for your interest and input! If you are willing to create a pull request with your changes I can have a look and merge them.

Additionally also thank you for pointing out these inconsistencies between documentation and the configuration files. 
We are currently working on a new version of CAMISIM (CAMISIM2.0 if you will) written with nextflow for pipelining. This new version hopefully solves a lot of bugs and conflicts which appear in CAMISIM since it is such a grown system. This version also will not need/use Perl anymore and we will have a consistent config file. I hope that this version will be done in the next few months.
