### ISSUE TITLE
Check dependencies

### ISSUE THREAD

**Issue by abremges** [CAMI-challenge/CAMISIM#15]
Not sure if implemented already, but do we have a way to check if **all** dependencies are installed before actually executing the pipeline?

**Comment by abremges** [comment]
@AlphaSquad @pbelmann Can you comment on this? If implemented (or too much hassle), please close.

**Comment by AlphaSquad** [comment]
With merging #25 , a requirements.txt was added and CAMISIM is running within a clean docker environment, so a `pip install requirements.txt` should install all dependencies required to run CAMISIM with at least the ART and wgsim version. Since NanoSim and PBsim are not part of CAMISIM (both GPL licensed), they would need to be installed separately.

**Comment by abremges** [comment]
@AlphaSquad will extend the "installation" part of the documentation in the wiki. If long reads are desired, PBsim and NanoSim (our branch) need to be manually installed. Then this issue can be closed.

**Comment by AlphaSquad** [comment]
Additional information has been added to the wiki
