### ISSUE TITLE
ERROR: [MetagenomeSimulationPipeline] 'MGV-GENOME-0364315' in line 117

### ISSUE THREAD

**Issue by Steven-GUHK** [CAMI-challenge/CAMISIM#152]
Hi! 

I encountered an error when running the _de novo_ method. "MGV-GENOME-0364315" is the beginning line of file 'MGVGENOME0364315.fna'. I put all the files right and get the file paths correctly. It seems that other files do not have the problem as the picture shows. Could you please tell me the problem? Thank you!
<img width="947" alt="error" src="https://user-images.githubusercontent.com/61462983/215314256-a692b1d9-e21d-479a-b171-31ab188335ad.png">

**Comment by AlphaSquad** [comment]
Hi, thank you for using CAMISIM. It is strange that this error occurs right at the end of CAMISIM (shuffle & anonymize is the last thing CAMISIM does). The only suspicion I have is that it is connected to the minus (`-`) in the fasta name, because there have been some issues with special characters before. Could you try removing the `-` from the fasta header and see if the problem persists?

**Comment by Steven-GUHK** [comment]
> 

Yes, you are right! It works after removing the '-' sign. Thank you!
