### ISSUE TITLE
Question about {out}/anonymous_gsa_pooled.fasta file and its corresponding bam file

### ISSUE THREAD

**Issue by Steven-GUHK** [CAMI-challenge/CAMISIM#153]
Hi!

I'm using CAMISIM to simulate 8 bacterial genomes into 8 samples. I want to get a fasta file that contains all contigs from all genomes (different from the single sample that contains only partial contigs of 8 genomes). I guess the _{out}/anonymous_gsa_pooled.fasta_ file should be the one. However, there is no bam file for this file, the output only has a bam file for each sample (_{out}/{sample_i}/bam_). I wonder whether I can use all the _{out}/{sample_i}{reads}/anonymous_reads.fq_ file and _{out}/anonymous_gsa_pooled.fasta_ file to generate the bam file using BWA? Or there is a parameter that I can change to generate the file? Thank you!

**Comment by AlphaSquad** [comment]
Hi, yes, you are right, the pooled gold standard is the file you mention. Unfortunately the bam-file is currently only generated temporarily. Depending on which information you need, you can use the `gsa_pooled_mapping.tsv` which points every contig to its location. There are bam files for each individual sample, so the "correct" way would be to `samtools merge` these. If you use a mapper like BWA or bowtie you might introduce mapping errors

**Comment by AlphaSquad** [comment]
Yes, exactly that was my suggestion, but the `bam` files here are mapped against the _reference genomes_ and not the gold standard. Since it seems you need the mapping of the reads against the gold standard then you probably need to generate the mapping yourself after all, sorry. 
That would probably work as you described in your original question.
