### ISSUE TITLE
Create Python package and conda recipe?

### ISSUE THREAD

**Issue by vinisalazar** [CAMI-challenge/CAMISIM#159]
Hi,

I'm looking to use CAMISIM but I'm finding the installation process a bit cumbersome. I was just wondering if there would be interest in packaging CAMISIM as a Python package, i.e. installable through pip, setuptools, or other tools like Poetry.

An added benefit of this would be the possibility of distributing CAMISIM through conda (by submitting it to Bioconda), avoiding the need to package all dependencies along with the CAMISIM source code.

If you are interested in that, I would be happy to draft a PR for your appreciation.

Thank you,
Vini

**Comment by AlphaSquad** [comment]
Hi Vinnie,
thank you very much for your comments and I wholeheartedly agree. We are currently working on an overhauled version of CAMISIM and having it containerized/dockerized as well as on bioconda is deifinitely on top of the list of things to do. Since CAMISIM will change quite a lot (e.g. moving to nextflow), we will not be doing this for the current version of CAMISIM. If you want to create a PR I will certainly have a look and merge it, otherwise you would have to wait a month or two™

**Comment by vinisalazar** [comment]
Dear @AlphaSquad 

Thanks for the quick response. Good to hear that a revamped version of CAMISIM is coming out. If that is the case, I'm happy to wait. Looking forward to using it.

Best,
V
