### ISSUE TITLE
A problem in testing one commond in the wiki 

### ISSUE THREAD

**Issue by fanqiedantang** [CAMI-challenge/CAMISIM#161]
Hi，
I encountered a problem while testing a command in the wiki. The command and problem are as follows.
command:
```python
python metagenome_from_profile.py -p defaults/mini.biom
``` 
problem:
![image](https://github.com/CAMI-challenge/CAMISIM/assets/90701916/ce53951f-2d83-452f-a24f-8797a6f7a10f)

Any help and information possible updates would be really appreciated. Thank you!

**Comment by AlphaSquad** [comment]
Hi, thank you for your interest in CAMISIM. The `from profile` mode downloads genomes from NCBI and in this case it seems like this download failed. Most of the times this is due to timeouts because of low download speed or connection failures. 
Unfortunately there is not much we can do on our end to prevent this
