### ISSUE TITLE
How to  speed up the microbiome simulation process using CamiSim

### ISSUE THREAD

**Issue by YunyunGao374** [CAMI-challenge/CAMISIM#163]
Hello,

I'm interested in finding ways to speed up the microbiome simulation process using CamiSim. I have a host genome and 20 bacterial genomes, totaling around 1.1 GB in size. My goal is to create a simulated microbiome population of approximately 6Gb. Currently, the simulation has been running for 190 hours, clearly, the speed remains quite slow.

I attempted to improve the speed by adjusting the max_processors parameter, trying values like 32, 64, and 128, but unfortunately, this didn't lead to any noticeable changes in the speed. Additionally, I experimented with running the command python ~/camisim/CAMISIM-master/metagenomesimulation.py test.ini --thread 20, hoping to utilize multiple threads, but encountered an error indicating that the --thread 20 option is not supported.

Given that I'm new to data analysis, I'm reaching out for assistance. Could you provide any guidance or suggestions to help me address these challenges? Thanks.

**Comment by AlphaSquad** [comment]
Hi, thank you for your interest in CAMISIM. CAMISIM can be somewhat slow, but 190 hours for a single sample of 6 GB seems excessive. Could you attach the config file you were using to find out more?
Unfortunately, CAMISIM in its current state has some parts which are not properly parallelised, so adding more cores and threads will not help much, particularly because most of the work is actually file I/O which is limited more by the speed of your hard drive(s) than your processor(s). A new version of CAMISIM using nextflow and thereby more efficiently utilising parallelisation will be out hopefully this fall

**Comment by AlphaSquad** [comment]
Note that you are creating 5 samples with 5.4 Gb each, so in total 27 Gb data. 190 hours still seems a lot, but it is not entirely impossible that CAMISIM is actually running that long. I have noticed a significant slowdown of CAMISIM when one of the input genomes is big - it seems your host genome is big (~1 GB?), so I suspect that to be the "culprit". If I remember correctly that slowdown unfortunately is because of the read simulation (using ART) and there is not much we can do. I suggest you let it run for a little longer and see if CAMISIM finishes in another few days.
Alternatively you could split up your host genome into e.g. 10 smaller parts and try if that speeds things up.

**Comment by YunyunGao374** [comment]
Yes, I tried to get five multiple replicated populations. Thanks so much for your suggestion, I will try to separate the big genome into several smaller parts to see the results, Thanks again.
