### ISSUE TITLE
2023-10-10 23:40:29 ERROR: [MetagenomeSimulationPipeline] 'Salmonella_enterica_Typhimurium_1898' in line 83

### ISSUE THREAD

**Issue by icbarron** [CAMI-challenge/CAMISIM#166]
Hi, I keep getting this error. Not sure what I am doing wrong.
[group2_viruses_community.txt](https://github.com/CAMI-challenge/CAMISIM/files/12864549/group2_viruses_community.txt)
[group2_viruses_id_to_genome.txt](https://github.com/CAMI-challenge/CAMISIM/files/12864568/group2_viruses_id_to_genome.txt)
[mini_config.txt](https://github.com/CAMI-challenge/CAMISIM/files/12864572/mini_config.txt)
These files are both .tsvs, or .ini, respectively, in the defaults folder.

I'm using https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/, with it modified to have the files contained under an NCBI heading.

**Comment by AlphaSquad** [comment]
Could you try running CAMISIM with replacing the taxonomy IDs by `2` (for bacteria) in your community file. If it runs through then we know the problem is still in the taxdump, if it doesn't then we will have to dig deeper - I have one or two hypotheses, but the taxdump still causing the problem seems to be the most likely to me.

**Comment by icbarron** [comment]
That fixed it.

**Comment by AlphaSquad** [comment]
The taxid's are only relevant for the profiling and profiling gold standards, so if you don't need these you should be able to use the created dataset as is. If you need/want the profiling then either probably format of the taxdump is still incorrect. Alternatively it might be due to the usage of the `strain` taxonomy ID. I know this is unsatisfactory but you could in a next step try replacing all the taxonomy IDs which refer to strains (i.e. `1454638` for `Salmonella_enterica_Typhimurium_1898`) to the corresponding higher level taxonomy IDs (i.e. `90371` for `Salmonella enterica subsp. enterica serovar Typhimurium` or `28901` for `Salmonella enterica`)

**Comment by icbarron** [comment]
I don't believe I need the gold standards, I just need basic mock communities for a viromics study.  I'll try going up a level or two from strain at some point in the future.
Thanks for the help! I appreciate it and CAMISIM.
