### ISSUE TITLE
should i download all the reference genomes of the species involved in the BIOM file？

### ISSUE THREAD

**Issue by fanqiedantang** [CAMI-challenge/CAMISIM#171]
Hi,
    I annotated a set of sequencing data using Kraken2 species annotation and obtained a species abundance table similar to 16s sequencing. The difference is that the first column is the species name rather than OTU id. Now I need to refer to this abundance table for sequencing data simulation. What necessary parameters do I need to set?
    thank you for any help !

**Comment by fanqiedantang** [comment]
> _No description provided._

**Comment by AlphaSquad** [comment]
Hi,
if you have a BIOM profile, you can directly use CAMISIMs `from_profile` mode which was created exactly for that use case. CAMISIM will automatically try to download similar genomes to the ones in the BIOM profile using the scientific name since there is not necessarily a 1 to 1 mapping.
Alternatively you would have to do this process yourself and find complete genomes corresponding to the scientific name
