### ISSUE TITLE
No file found for all the reads of the sample in the output

### ISSUE THREAD

**Issue by shussin245** [CAMI-challenge/CAMISIM#182]
Hi!

Thank you so much for your work on CAMISIM and your help on this subject. I am trying to simulate reads for 12,000 total sequences. Each of the 1,000 species has a certain number of strains (a total of 11,000) strains. I have run CAMISIM _de novo_ for each species+strain set. Say I have species A with 1 strain, species B with 2 strains, and species C with 3 strains. I have ran CAMISIM for each species and its strains (only one sample) and set the size of the sample to be the total number of bases for the species+strain set.

Do you think I should run CAMISIM individually for each set or is it possible to combine everything into a single run? Would it be computationally expensive?

Furthermore, when I ran CAMISIM for each species+strain set, I didn't see an output file with all the reads of the sample. I just saw a read file for each of the sequences. Additionally, I was given two files for the reads. For example, if I ran CAMISIM for species A, I would have two sequences total (the reference sequence and the strain sequence) and my output would look like this:

SPECIES_A1.fq.gz
SPECIES_A12.fq.gz
SPECIES_A_STRAIN_01.fq.gz
SPECIES_A_STRAIN_02.fq.gz

I would have two files of reads for the same sequence. What do the two files mean? Are the reads split into two files or are they the same file?

Thank you so much in advance for your help on this and I'm looking forward to hearing from you. Please let me know if I can provide anymore information on my issue.

**Comment by AlphaSquad** [comment]
Hi, thank you for your interest in CAMISIM, let me try to answer your questions:
```Do you think I should run CAMISIM individually for each set or is it possible to combine everything into a single run? Would it be computationally expensive?```
CAMISIMs running time and memory consumption is mainly dependent on the amount of Gigabases you create, not necessarily the number of species/strains. But if you don't need gold standards over your entire data set with all the strains, then it is probably more efficient to run CAMISIM multiple times - otherwise CAMISIM will try to generate a gold standard e.g. assembly over all of your 1,000 samples which will probably take a while and is something you might not need?
```I just saw a read file for each of the sequences.```
You probably turned off the anonymisation of CAMISIM? Then CAMISIM will create a read file per strain/species; you can just append all of the read files together which would be equivalent to your sample or you could turn anonymisation back on then you should receive just one read-file.
```I would have two files of reads for the same sequence. What do the two files mean? Are the reads split into two files or are they the same file?```
You probably used the ART short-read simulator for simulating your reads? ART simulates paired-end reads like modern Illumina sequencers produce, the two files correspond to the forward and reverse reads. With the default parameters the read length of ART is 150 base pairs with an insert size of 270 base pairs, so the first read in the first file will cover the first 150 base pairs of the 270 bases insert size and the first read in the second file will cover the last 150 base pairs of the 270 base insert size which in turn means that there is ~30bp overlapping in the middle.

**Comment by shussin245** [comment]
Thank you so much for your response! I will run CAMISIM again, but include all the species and strains and see how that goes. Thank you for the clarification on the output files. I just read a little bit more about paired-end reads and I think I understand it now. I will close this issue, but I'll be sure to reach out if I have any more questions. Thanks again!
