### ISSUE TITLE
Question about simulating metagenomes with plasmids

### ISSUE THREAD

**Issue by fnew** [CAMI-challenge/CAMISIM#56]
I want to simulate metagenomes with plasmids. My question is specifically how to include plasmids in the pipeline. I am planning to simulate metagenomes from 25 bacterial genomes, one of which has a plasmid. Should I take the plasmid out of the bacterial genome and include it as a separate fasta file? 

The manual says, "The absolute abundance of the circular elements can be set to be like 15 times as high as the abundance of the microbial genomes, to replicate high natural plasmid abundances." This makes me think that the plasmids should be kept separate and the community abundances specified in separate distribution files?

The example files that come with CamiSim include two plasmid files, "plasmid_metadata_v2.3_filtered.tsv" and "plasmid_path.tsv". It's not clear to me if these are to be used to create a community of only plasmids, or if they are used in conjunction with the genomes in the metadata.tsv file. In the example file, "default_config.ini", they are used in the second community design. Can you explain that a little bit more as well? Should I keep my plasmids separate, then in the config file specify two communities, 1) with genomes, 2) with plasmids?

**Comment by AlphaSquad** [comment]
Thank you for your interest in CAMISIM.
There are actually multiple ways of including plasmids into a CAMISIM data set, which way you want to use depends on the goal you want to achieve. Let me describe three different ways:

1) Do not alter anything. It is absolutely no problem if your reference fasta file contains more than one sequence. Every time a read is simulated it is chosen randomly from one of the sequences in your fasta file.
This means, that the number of reads belonging to your plasmid is proportional to the size of the plasmid relative to the genomes' sequence. The total coverage of the plasmid and the (bacterial) genome will be (roughly) the same and in the gold standard and all the mapping files it is easy to trace a plasmid and it's correspondence to the genome. In your case this is probably what I would recommend.

2) Use the community feature, like described in the manual/used in the CAMI1 challenge. We did not have plasmids/circular elements "belonging" to a certain genome. We only used the information that plasmids seem to be abundant in metagenomes. Defining a second community with its own distribution but an overall abundance of 15 times the abundance of the genomes of the first community ensured that the much shorter plasmids will make up a larger portion of the metagenome (i.e. the relative coverage of the plasmids is 15 times that of the genomes, but since they are sometimes up to 1000 times shorter, the absolute abundance of plasmids in the metagenome will still be low).
Using this feature does not allow the (easy) tracking of plasmids to their "corresponding genomes" and will decorrelate abundances between genome and plasmid, which might not be what you expect/desire

3) The third option requires more manual effort but may increase the realism of the data set: You could separate the plasmid from the genome and manually edit some files to ensure a) that the plasmid will seem circular in the simulation and b) will appear in the desired relative abundance towards the bacterial genome.

Since this is already a quite lengthy text, I will not describe the third option here in full; if you are interested in that option, please let me know and I can possibly add a section to the manual.

**Comment by fnew** [comment]
Thank you so much for your detailed response. This has helped to clarify things for me. For my purposes, option 1 might work, but I think that option 3 is really what I am looking for. An amendment to the manual going into detail about that would be really useful!

**Comment by AlphaSquad** [comment]
If you send me your email address (to adrian.fritz@helmholtz-hzi.de) I can give you a run-through of our ideas how to treat plasmids. 
Parts of this are going to be part of the CAMI2 challenge which is unpublished so far, so I'd rather send the details to you personally than disclosing it here on GitHub right now if that is fine for you.
