### ISSUE TITLE
Simulate metagenome from abundance profile of private genomes

### ISSUE THREAD

**Issue by joshamilton** [CAMI-challenge/CAMISIM#59]
I would like to simulate a metagenome from an abundance profile I specify, using exclusively private genomes (similar to issue #58). I have updated my config file to reference `id_to_genome`, `metadata`,  and `distribution_file` files that I've created. However, when I run `metagenome_from_profile.py -c hamilton/config.ini`, I receive the following error:

```
Traceback (most recent call last):
  File "/Applications/CAMISIM/metagenome_from_profile.py", line 87, in <module>
    config = GG.generate_input(args) # total number of genomes and path to updated config
  File "/Applications/CAMISIM/scripts/get_genomes.py", line 283, in generate_input
    tax_profile = read_taxonomic_profile(args.profile, config, args.samples)
  File "/Applications/CAMISIM/scripts/get_genomes.py", line 26, in read_taxonomic_profile
    table = biom.load_table(biom_profile)
  File "/anaconda3/envs/camisim/lib/python2.7/site-packages/biom/parse.py", line 658, in load_table
    with biom_open(f) as fp:
  File "/anaconda3/envs/camisim/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/anaconda3/envs/camisim/lib/python2.7/site-packages/biom/util.py", line 443, in biom_open
    if os.path.getsize(fp) == 0:
  File "/anaconda3/envs/camisim/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
TypeError: coercing to Unicode: need string or buffer, NoneType found
Exception AttributeError: "'NoneType' object has no attribute '_map_logfile_handler'" in <bound method LoggingWrapper.__del__ of <scripts.loggingwrapper.LoggingWrapper object at 0x7fa2e0acfa50>> ignored
```

`metagenome_from_profile.py` is trying to read in a BIOM file containing my abundance distribution. When I specify a BIOM file and run `metagenome_from_profile.py -c hamilton/config.ini -p hamilton/dist.biom`, I receive another error:

```
Traceback (most recent call last):
  File "/Applications/CAMISIM/metagenome_from_profile.py", line 87, in <module>
    config = GG.generate_input(args) # total number of genomes and path to updated config
  File "/Applications/CAMISIM/scripts/get_genomes.py", line 283, in generate_input
    tax_profile = read_taxonomic_profile(args.profile, config, args.samples)
  File "/Applications/CAMISIM/scripts/get_genomes.py", line 42, in read_taxonomic_profile
    lineage = table.metadata(otu,axis="observation")["taxonomy"]
TypeError: 'NoneType' object has no attribute '__getitem__'
Exception AttributeError: "'NoneType' object has no attribute '_map_logfile_handler'" in <bound method LoggingWrapper.__del__ of <scripts.loggingwrapper.LoggingWrapper object at 0x7f9ba0ebfa50>> ignored
```

Can you provide some guidance on the proper syntax and/or configuration I should use? I have created a minimal example in [my fork of the repo](https://github.com/joshamilton/CAMISIM/tree/hamilton). Thanks!

**Comment by AlphaSquad** [comment]
Thank you for your detailed problem description and the fork.
If you want to set your distributions manually and do not want to read abundances from a BIOM file, which I assume is want you want to do, then you don't need to use the `metagenome_from_profile.py` script, but the `metagenomesimulation.py` instead.
So your command would become `metagenomsimulation.py hamilton/config.ini`
Additionally there is a few things I needed to change to get your example to run with your fork:
1. Your config file had the "log_mu", "log_sigma" and "max_strains_per_otu" in the `[Main]` section of the config, they are supposed to be in the `[community0]` section
2. The paths to your metadata/genomes_to_id/distribution files have to be set relative to the main folder of CAMISIM (or even better, absolute paths). Additionally your distribution file is called `hamilton/dist.tsv`, in the `config.ini` you call it `comm0-dist0.tsv`
3. Your genomes_to_id file contained much more genomes than actually present in your refGenomes folder (probably since you did not want to upload them all), this will also cause problems; in the minimal examples you will have to remove all these genomes from the genomes_to_id.tsv file (and also the metadata.tsv)
4. Your metadata file did not contain NCBI_IDs for your genomes, this option is required to produce the taxonomic binning and profiling gold standards. If you are not interested in these, you can just give an arbitrary (but valid) NCBI tax ID to your genomes, in my minimal example I chose the tax ID 2 (for 'bacteria') for your 3 input genomes

After changing these options, I was able to run `metagenomesimulation.py hamilton/config.ini` successfully.
Please let me know if these steps worked for you!

**Comment by joshamilton** [comment]
Thanks @AlphaSquad for such a rapid response and helpful explanation. Camisim is now working for me!
