### ISSUE TITLE
output folder

### ISSUE THREAD

**Issue by plesan** [CAMI-challenge/CAMISIM#61]
Hi,

I run camisim with profile abundance to produce metagenomics data, and only step "read simulator" (no comunity design). It resulted in a folder sample_xx/contigs, bam, reads, but no "fastq" folder as you mentioned in the manual. I wonder if I missed something. It makes more sense that I have a final fastq file per sample, and I do not see it in my results. Could you please help? Thanks in advances.

Best regards,

**Comment by plesan** [comment]
Hi again, 
I noticed that the sample output names do not correspond to the original names provided in profile abundance. Is it normal or something wrong with it? Thanks.

**Comment by plesan** [comment]
Another question about the parameters of simulator:
You wrote: The chosen read simulator then generates reads, using the technology and properties (like read length, insert size or error rates if applicable) as specified by the user, sampling each genome proportionally to the specified abundance in the community.

Where can I customize the read properties? Thanks.

**Comment by AlphaSquad** [comment]
Hi,
this is indeed an error in the manual, I updated it now. The folder in which the reads are is called `reads` now, can you check that there is one `anonymous_reads.fq.gz` in that folder? If you did not anonymize your sample, there might be one read file per genome.
The sample output names will always be `yyyy.mm.dd_hh.mm.ss_sample_{i}`, the name you provide will just be used for mapping the contigs/reads to the genomes - if I understand your question correctly.
For the reads: You can set a few options in the config file, i.e. fragment/read size, fragment/read size standard deviation and choose an error profile. For ART the mbarc error profile is probably the one you will want to use, if you don't want to train a model yourself. If you want to use another read simulator and can't find your desired read properties, please let me know.

**Comment by plesan** [comment]
Hi,

Thanks. Yes, you answered the two first points about the folder reads and the sample name. for the same name, it means I need to rename to the correct name afterward. Is it right?

I used nanosim, can you please indicate which file I need to use.

Another question about the sample size. I want to produce metagenomics samples with sequencing depth and coverage different, so I need to run different times with corresponding default_config.ini and profile abundance? do you have an option to determine different sizes of different samples in the same run? It would be great.

For the read length and the number of reads, if I run, for example, 3 samples, the distribution of reads length and the number of reads are similar. Is it expected right?

Kind regards

**Comment by AlphaSquad** [comment]
Yes, right, if you want your sample folders/files to have a specific name you would need to rename them.

Since NanoSim is published under GPL and we want CAMISIM under the Apache license, we cannot provide a NanoSim installation directly, so you will need your own installation. [NanoSim](https://github.com/bcgsc/NanoSim) comes with its own script for creating error models, for which you will need a set of NanoSim reads and their alignment to a reference genome. We have [two models](https://github.com/CAMI-challenge/CAMISIM/tree/nanosim/tools/nanosim_profile) available for that, which you can already find in the `nanosim` branch - it is still experimental though. 
Currently the path to the error profile is hardcoded in line 521 of the [readsimulationwrapper.py](https://github.com/CAMI-challenge/CAMISIM/blob/nanosim/scripts/ReadSimulationWrapper/readsimulationwrapper.py), it is on my todo list to change that.

Your suggestion of different depths in different samples is an interesting one, I will have to look into that. Right now you would have to create multiple configuration files, yes. 

Since in all the samples the depth is the same and the error profile is the same, I would expect the distribution of read lengths and number of reads to be similar in multiple runs, yes. NanoSim does not offer an option for changing read lengths etc directly, this information is purely drawn from the created error profile; a possible solution would be to have different profiles for different samples, but then, also, you would need multiple configuration files though.

**Comment by plesan** [comment]
Thanks for your replies. Yes, it would be great that you have an option to have different sequencing depth in different samples. For now, the "genomes" folder is replicated for each run, and I think it is not necessary. For instance, I run 100 samples with different sizes, and I have 100 genomes folders. so far, I removed them manually to have more space.

**Comment by plesan** [comment]
Hi,

For the mode of simulation, I want to use "replicates" mode. Can you please tell me where I can customize the number of replicates. I do see two parameters:
# how many different samples?
number_of_samples=

# how many communities
num_communities=

Are they used for the replicates parameters? 

Thanks

**Comment by AlphaSquad** [comment]
That is true, I will look into how this can be achieved.
The "replicates" mode is described in the [paper](https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-019-0633-6): " Based on an initial log-normal distribution D0, n samples are created by adding Gaussian noise to this initial distribution"
The number of replicates per genome will be the number of samples

**Comment by plesan** [comment]
The abundance profile formatted as "Biom" contains a taxonomy lineage column. 
Please let me know if I understand correctly the following things:
- The lineage considers furthest lineage as strain or species, is it right? 
- If two genomes have the same lineage, will two genomes be considered for the simulation? The output folder "genome" will contain more genomes than the number of genomes that I gave in the abundance profile. To illustrate, the abundance profile has only 10 genomes, but the output folder "genome" contains more than 10 genomes. 

Some questions:
- I  notice that two genome links pointed out to Genome53.0.0 and Genome53.0.1. And I do not understand why? Of note, I gave unique links in the genome_to_id.tsv;
- do I need to give all information in metadata.tsv file?
For example:
Genome53.0	simulation_nanopore/CAMISIM/genomes.db.506sp/genomes/GCA_000162015.1_ASM16201v1_genomic.fna

metadata.tsv
Genome_ID	OTU	NCBI_ID	novelty_category
Genome53.0	0	411483	known_train

But the output displays:
Genome_ID	OTU	NCBI_ID	novelty_category
Genome53.0.1	541000	663278	new_strain
Genome53.0.0	541000	292800	new_strain
Where are the number of OTU from? and the NCBI_ID has been changed too!?

These things caused the difficulty to control and verify the abundance after the simulation.

Can you please help? Thanks.

**Comment by AlphaSquad** [comment]
Please make sure that you are using the correct python script for simulation. If you want to use your own genomes and your own distribution, the script you want to use will be `metagenomesimulation.py` and given only the config file as input. If you have a BIOM profile and genomes available, only then you should use the `metagenome_from_profile.py` script. The latter one will ignore the `distribution_file_paths` option from the config since it will create its own abundances based on the biom file. It will also ignore the metadata.tsv input file since, again, it will create these from the downloaded genomes. You can use the _from profile_ script with your own genomes using the `--ar` option, but for me it sounds like you would want to use the `metagenomesimulation.py` script.

**Comment by plesan** [comment]
To make clear to you, I want to simulate metagenomics reads from my genomes with their abundances. In your opinion, I would use metagenomessimulation.py. This script needs only config file.
Where do I give the abundance wanted? is it in the metadata.tsv (OTU number?) knowing that the abundance is a ratio (relative abundance).

**Comment by AlphaSquad** [comment]
The config file has an option called `distribution_file_paths`, where you can give CAMISIM the path to files containing the abundances of every genome (one file per sample). See also [here](https://github.com/CAMI-challenge/CAMISIM/wiki/File-Formats) under 'distribution_file_paths'

**Comment by plesan** [comment]
Hi,

It works better now because I get the genomes wanted and I use metagenomesimulation.py.  I still have other questions 
-  In general the abundance in simulated data was relatively correlated to reference abundance (pearson 0.8). When I filtered the quality of reads by mapq score (minimap2), the correlation was better (pearson 0.97). My expectation is the correlation should be good also before the filtering by mapq score. I think it might be the ratio of sequencing error is high!?  Do you have a parameter to determine the noise of sequencing? 

- Second, the correlation is not 100% because one sample crashed. That is, one genome remained few reads after aligning back to the reference genome and the abundance was completely wrong compared to the reference too. and I do not have yet explication.

- Third, in metadata.tsv I determine the OTU is 0 for all genome. because I do not see the interest about this variable? should I put a correct number in OTU?

- Fourth, metadata file needs genome id, OTU, NCBI ID and name. I wonder would it be possible not to give alias of each genome (genome1, genome2)? does the script work if the column "genome_id" is the taxon id (because it avoids to change the name afterward in the result (e.g. folder reads))?

Thanks.

**Comment by AlphaSquad** [comment]
I'll try to address these points:
 - You are still using the NanoSim mode, I guess? Which model did you use, the ecoli one or starting with SRR? Unfortunately NanoSim does not offer such an option, the only thing you can do is train a model.
 - Without an error log I also cannot really tell what might have happened there, sorry.
 - You are right, since you are giving all the abundances and want to use all genomes, the OTU value is irrelevant
 - Using the taxonomy ID as genome ID should be no problem

**Comment by plesan** [comment]
- Yes, I use nanosim with ecoli model. What is the difference between E.coli and SRR model?
- I can send you error file, but I will definitely try the second model.
and I will try with taxonomy ID instead of genome ID.

**Comment by plesan** [comment]
I try SRR model, but one file is missing 
"No such file or directory: 'tools/nanosim_profile/SRR6394747_profile_unaligned_length_ecdf"

**Comment by AlphaSquad** [comment]
There is an updated version online on the nanosim branch with a corresponding config file (`defaults/mini_nanosim.ini`) which you can try. This model was trained using a Nanosim run of the MBARC-26 community, described [here](https://www.nature.com/articles/sdata201681)
