### ISSUE TITLE
Genome coverage

### ISSUE THREAD

**Issue by drdee255** [CAMI-challenge/CAMISIM#63]
I am trying to simulate data for testing purpose in which I want to be assure that all the regions from my all genomes are represented in metagenomes.

How should I proceed?

**Comment by AlphaSquad** [comment]
Unfortunately there is no way to entirely ensure that all regions of your genome will be present since the read sampling from the genomes is random. 
If you set the abundance of your genomes high enough though, such that the average coverage of your genomes is somewhere above 10x it is very likely that most parts of the genomes will be covered by reads. You could try to do so and then look at the gold standard assembly/read mapping files to check whether all the regions of your genome(s) are represented.
